[package]
name = "dva_smp_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
anyhow = "1.0.71"
slint = "1.0.2"
tokio = "1.28.2"

[build-dependencies]
slint-build = "1.0.2"
