[package]
name = "dva_smp_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
clone-macro = "0.1.0"
directories = "5.0.1"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
slint = "1.0.2"
tokio = { version = "1.28.2", features = ["full"] }
webbrowser = "0.8.10"

[build-dependencies]
slint-build = "1.0.2"
