[package]
name = "dva_smp_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
base16ct = "0.2.0"
clone-macro = "0.1.0"
directories = "5.0.1"
futures = "0.3.28"
registry = "1.2.3"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
semver = "1.0.17"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
sha1 = { version = "0.10.5", features = ["asm"] }
slint = "1.0.2"
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.3"
webbrowser = "0.8.10"

[build-dependencies]
slint-build = "1.0.2"

# Building darwin images:
# git clone https://github.com/cross-rs/cross
# cd cross
# git submodule update --init --remote
# sed -i s/17bb5e2d0a46533c1dd525cf4e9a80d88bd9f00e/ed079949e7aee248ad7e7cb97726cd1c8556afd1/ docker/cross-toolchains/docker/darwin.sh
# wget https://github.com/joseluisq/macosx-sdks/releases/download/13.1/MacOSX13.1.sdk.tar.xz -O docker/MacOSX13.1.sdk.tar.xz
# cargo build-docker-image x86_64-apple-darwin-cross --tag local --build-arg MACOS_SDK_FILE=MacOSX13.1.sdk.tar.xz
# The resulting image will be named ghcr.io/cross-rs/x86_64-apple-darwin-cross:local
[package.metadata.cross.target."x86_64-apple-darwin"]
image = "registry.vanutp.dev/vanutp/cross-darwin/x86_64-apple-darwin-cross:latest"
[package.metadata.cross.target."aarch64-apple-darwin"]
image = "registry.vanutp.dev/vanutp/cross-darwin/aarch64-apple-darwin-cross:latest"
