on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}
      LAUNCHER_NAME: ${{ vars.LAUNCHER_NAME }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install poetry==1.8.3
      - run: mkdir .venv
      - run: poetry install --no-root
      - run: poetry run pyinstaller --onefile --copy-metadata readchar --name $LAUNCHER_NAME --exclude-module PIL --icon assets/$LAUNCHER_NAME.png launch.py
      - if: ${{ github.ref }} == master
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: no
      - if: ${{ github.ref }} == master
        env:
          TARGET_FILENAME: ${{ format(fromJSON('{"windows-latest":"{0}.exe","ubuntu-latest":"{0}_linux","macos-latest":"{0}_macos"}')[matrix.os], env.LAUNCHER_NAME) }}
          SHA1SUM: ${{ fromJSON('{"windows-latest":"sha1sum","ubuntu-latest":"sha1sum","macos-latest":"shasum"}')[matrix.os] }}
        run: |
          mv dist/* dist/$TARGET_FILENAME || true
          $SHA1SUM dist/$TARGET_FILENAME | cut -f1 -d ' ' > dist/$TARGET_FILENAME.sha1
      - if: ${{ github.ref }} == master
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null dist/* $SERVER_USER@$SERVER_ADDR:$SERVER_PATH/
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
