on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install poetry==1.5.1
      - run: mkdir .venv
      - run: poetry install --no-root
      - run: poetry run pyinstaller --onefile --name dva_smp_launcher --exclude-module PIL --icon assets/dva_smp_launcher.png launch.py
      - if: ${{ github.ref }} == master
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - if: ${{ github.ref }} == master
        env:
          TARGET_FILENAME: ${{ fromJSON('{"windows-latest":"dva_smp_launcher.exe","ubuntu-latest":"dva_smp_launcher_linux","macos-latest":"dva_smp_launcher_macos"}')[matrix.os] }}
          SHA1SUM: ${{ fromJSON('{"windows-latest":"sha1sum","ubuntu-latest":"sha1sum","macos-latest":"shasum"}')[matrix.os] }}
        run: |
          mv dist/* dist/$TARGET_FILENAME || true
          $SHA1SUM dist/$TARGET_FILENAME | cut -f1 -d ' ' > dist/$TARGET_FILENAME.sha1
      - if: ${{ github.ref }} == master
        run: scp dist/* $SERVER_USER@$SERVER_ADDR:$SERVER_PATH/
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
