on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SERVER_BASE: ${{ vars.SERVER_BASE }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install poetry==1.5.1 pyinstaller==5.12.0
      - run: mkdir .venv
      - run: poetry install --no-root
      - run: python write_build_cfg.py
      - run: poetry run pyinstaller --onefile --name dva_smp_launcher launch.py
      - if: ${{ github.ref }} == master
        uses: shimataro/ssh-key-action@685d0f20da72e4b53cc81d373a2ed0a867770e46
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - if: ${{ github.ref }} == master
        env:
          TARGET_FILENAME: ${{ fromJSON('{"windows-latest":"dva_smp_launcher.exe","ubuntu-latest":"dva_smp_launcher_linux","macos-latest":"dva_smp_launcher_macos"}')[matrix.os] }}
        run: |
          command -v shasum && alias sha1sum shasum
          mv dist/* dist/$TARGET_FILENAME
          sha1sum dist/$TARGET_FILENAME | cut -f1 -d ' ' > dist/$TARGET_FILENAME.sha1
      - if: ${{ github.ref }} == master
        run: scp dist/* $SERVER_ADDR:$SERVER_PATH/
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
