on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    env:
      HAS_SSH_KEY: ${{ secrets.SSH_KEY != '' }}
      HAS_SERVER_USER: ${{ secrets.SERVER_USER != '' }}
      HAS_SERVER_ADDR: ${{ secrets.SERVER_ADDR != '' }}
      HAS_POST_DEPLOY_SCRIPT: ${{ secrets.POST_DEPLOY_SCRIPT_PATH != '' }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Set environment variables
        run: |
          echo "VERSION=$GITHUB_SHA" >> $GITHUB_ENV
          echo "LAUNCHER_NAME=${{ vars.LAUNCHER_NAME }}" >> $GITHUB_ENV
          DATA_LAUNCHER_NAME=$(echo "${{ vars.LAUNCHER_NAME }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
          echo "DATA_LAUNCHER_NAME=$DATA_LAUNCHER_NAME" >> $GITHUB_ENV
          echo "VERSION_MANIFEST_URL=${{ vars.VERSION_MANIFEST_URL }}" >> $GITHUB_ENV
          if [ -n "${{ vars.AUTO_UPDATE_BASE }}" ]; then echo "AUTO_UPDATE_BASE=${{ vars.AUTO_UPDATE_BASE }}" >> $GITHUB_ENV; fi

      - name: Build the launcher
        run: |
          mkdir -p build
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cargo build --bin launcher --profile release-lto
            mv "target/release-lto/launcher.exe" "build/${LAUNCHER_NAME}.exe"
            echo "$VERSION" > build/version_windows.txt
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --bin launcher --profile release-lto
            mv "target/release-lto/launcher" "build/${DATA_LAUNCHER_NAME}"
            echo "$VERSION" > build/version_linux.txt
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cp "launcher/assets/$DATA_LAUNCHER_NAME.png" "launcher/assets/icon.png"

            which cargo-bundle || cargo install cargo-bundle
            rustup target add x86_64-apple-darwin aarch64-apple-darwin

            # Build Intel binary directly (with older deployment target)
            export MACOSX_DEPLOYMENT_TARGET=10.12
            cargo build --bin launcher --profile release-lto --target x86_64-apple-darwin
            
            # Build ARM binary as part of bundle (with newer deployment target)
            export MACOSX_DEPLOYMENT_TARGET=11.0
            cargo bundle --bin launcher --profile release-lto --target aarch64-apple-darwin

            mkdir -p app
            mv "target/aarch64-apple-darwin/release-lto/bundle/osx/Potato Launcher.app" "app/$LAUNCHER_NAME.app"

            # Update permission descriptions (required for simple voice chat and some other mods)
            plutil -replace NSCameraUsageDescription \
              -string "A Minecraft mod wants to access your camera." \
              "app/$LAUNCHER_NAME.app/Contents/Info.plist"
            plutil -replace NSMicrophoneUsageDescription \
              -string "A Minecraft mod wants to access your microphone." \
              "app/$LAUNCHER_NAME.app/Contents/Info.plist"
            plutil -insert NSEnableAutomaticCustomizeTouchBarMenuItem \
              -bool false \
              "app/$LAUNCHER_NAME.app/Contents/Info.plist"
            plutil -insert NSFunctionBarAPIEnabled \
              -bool false \
              "app/$LAUNCHER_NAME.app/Contents/Info.plist"

            # Create universal binary
            lipo -create -output "app/$LAUNCHER_NAME.app/Contents/MacOS/launcher" \
              "target/x86_64-apple-darwin/release-lto/launcher" \
              "app/$LAUNCHER_NAME.app/Contents/MacOS/launcher"

            codesign --force --deep --sign - "app/$LAUNCHER_NAME.app"

            ln -s /Applications app/Applications

            DMG_FILENAME="${LAUNCHER_NAME}.dmg"

            # CI runner sometimes fails with "hdiutil: create failed - Resource busy", so retry a few times
            retry=0
            max_retries=5
            until [ $retry -ge $max_retries ]
            do
              hdiutil create "$DMG_FILENAME" -ov -volname "$LAUNCHER_NAME" -fs HFS+ -srcfolder "app/" && break
              retry=$((retry+1))
              echo "Retrying hdiutil create... ($retry/$max_retries)"
              sleep 5
            done

            mv "$DMG_FILENAME" build/

            mv "app/$LAUNCHER_NAME.app" "app/update.app"
            tar -czvf "build/${DATA_LAUNCHER_NAME}_macos.tar.gz" -C app "update.app"

            echo "$VERSION" > build/version_macos.txt
          fi

      - name: Set up SSH
        if: ${{ github.ref == 'refs/heads/master' && env.HAS_SSH_KEY == 'true' && env.HAS_SERVER_USER == 'true' && env.HAS_SERVER_ADDR == 'true' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: no

      - name: Deploy to server
        if: ${{ github.ref == 'refs/heads/master' && env.HAS_SSH_KEY == 'true' && env.HAS_SERVER_USER == 'true' && env.HAS_SERVER_ADDR == 'true' }}
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/* $SERVER_USER@$SERVER_ADDR:$SERVER_PATH/

      - name: Run post-deploy script
        if: ${{ github.ref == 'refs/heads/master' && env.HAS_SSH_KEY == 'true' && env.HAS_SERVER_USER == 'true' && env.HAS_SERVER_ADDR == 'true' && env.HAS_POST_DEPLOY_SCRIPT == 'true' }}
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
          POST_DEPLOY_SCRIPT_PATH: ${{ secrets.POST_DEPLOY_SCRIPT_PATH }}
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_ADDR "bash \"$POST_DEPLOY_SCRIPT_PATH\""

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: launcher-${{ matrix.os }}
          path: build/*
